# Site settings
title: Dex Hunter blog 
description: "Musings of a Computer Scientist."
baseurl: "/hackme" # the subpath of your site, e.g. /blog
url: "https://dexhunter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: DexHunter 

# Build settings
markdown: kramdown
theme: minima 
disqus:
    shortname: dexhunter
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
